FileCreateDir,%Install%
  FileCreateDir,%Install%\ahk
    FileInstall,ahk\sc.ahk,%Install%\ahk\sc.ahk,1
    FileInstall,ahk\sx.ahk,%Install%\ahk\sx.ahk,1
    FileInstall,ahk\hotkey_guis.ahk,%Install%\ahk\hotkey_guis.ahk,1
    FileInstall,ahk\install.ahk,%Install%\ahk\install.ahk,1
    FileInstall,ahk\var.ahk,%Install%\ahk\var.ahk,1
  FileCreateDir,%Install%\img
    FileInstall,img\icon.ico,%Install%\img\icon.ico,1